import Footer from "./_footer";
import Navbar from "./_navbar";
import "./globals.css";

export const metadata = {
  title: "Web 3.0 NFT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <div className="bg-[#1d1f2b]">
          <Navbar />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
